### ISSUE TITLE
Possible Leak when exec fails

### ISSUE THREAD

**Issue by danfyty** [SOII-2016/jucilei#2]
Running: valgring ./test lsa (./test receives a command and uses runcmd to execute it), gives the output in output.txt
[output.txt](https://github.com/SOII-2016/jucilei/files/252312/output.txt)

To execute the exact same test do:
make test_leak

**Comment by danfyty** [comment]
I think it's fixed now on branch mem_leak
[output.txt](https://github.com/SOII-2016/jucilei/files/252452/output.txt)

**Comment by monacofj** [comment]
Indeed!!! I have fixed also in posixeg.
Thanks a lot. Clear to merge!
